apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: service2
    version: v1
  name: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
      version: v1
  template:
    metadata:
      labels:
        app: service2
        version: v1
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
          image: service2:v1
          imagePullPolicy: IfNotPresent
          name: service2
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
          securityContext:
            privileged: false
