apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: myproject
spec:
  ports:
    - name: 8082-tcp
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    deploymentconfig: "service2"
  sessionAffinity: None
  type: ClusterIP